//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlapianiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOSITIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISPOSITIVO()
        {
            this.REGISTROes = new HashSet<REGISTRO>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string No_Serie { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Sujeto { get; set; }
    
        public virtual SUJETO SUJETO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO> REGISTROes { get; set; }
    }
}
