//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlapianiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACION_SUJETO_USUARIO
    {
        public int id { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> Sujeto { get; set; }
    
        public virtual SUJETO SUJETO1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
