//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlapianiServer
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.RELACION_SUJETO_USUARIO = new HashSet<RELACION_SUJETO_USUARIO>();
        }
    
        public string id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Tipo { get; set; }
        public bool Tutor { get; set; }
        public string Clave { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Numero { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELACION_SUJETO_USUARIO> RELACION_SUJETO_USUARIO { get; set; }

        public USUARIO(string json)
        {
            JObject jObject = JObject.Parse(json);
            JToken jUser = jObject["usuario"];
            id = (string)jUser["id"];
            //Nombre = (string)jUser["Nombre"];
            //ApellidoP = (string)jUser["ApellidoP"];
        }
    }
}
